package common.core.worker;

import io.netty.channel.Channel;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

public class WorkerGlobal {

    private static Logger logger = LogManager.getLogger(WorkerGlobal.class.getName());
    private WorkerGlobal (){}

    public static WorkerGlobal masterGlobal = new WorkerGlobal();

    public static WorkerGlobal getInstance(){
        return masterGlobal;
    }

    private String currentWorkerId;
    private Channel syncBootstrapChannel;

    /**
     * Register workerId which has been generated by master
     * @param workerId
     */
    public void registerWorkerId(String workerId){
        logger.info("register worker id : " + workerId);
        this.currentWorkerId = workerId;
    }

    public String getCurrentWorkerId(){
        return this.currentWorkerId;
    }

    public void registerMaster(Channel channel){
        this.syncBootstrapChannel = channel;
    }

    public Channel getMasterChannel(){
        return this.syncBootstrapChannel;
    }


}
